//This code prints the version number and a brief message when entering teach mode.

void PrintInstructions(){ //CALIBRATING: PLEASE TYPE THE FOLLOWING KEYS

USBSendString("USB TYPEWRITER");
USBSend(KEY_9,UPPER);
USBSend(KEY_T,UPPER);
USBSend(KEY_M,UPPER);
USBSend(KEY_0,UPPER);
USBSend(KEY_ENTER);
USBSendString("VER");
USBSend(KEY_SPACE,UPPER);
USBSend(KEY_4,LOWER);
USBSend(KEY_PERIOD,LOWER);
USBSend(KEY_1,LOWER);
USBSend(KEY_ENTER);
USBSendString("CALIBRATING");
USBSend(KEY_PERIOD);
USBSend(KEY_PERIOD);
USBSend(KEY_PERIOD);
USBSend(KEY_ENTER,LOWER);
USBSendString("TYPE THE FOLLOWING KEYS");
USBSend(KEY_PERIOD,LOWER);
USBSend(KEY_PERIOD,LOWER);
USBSend(KEY_PERIOD,LOWER);
USBSend(KEY_ENTER);
}

